---

- name: Update the apt cache
  apt:
    cache_valid_time: 3600
    update_cache: yes

- name: ClamAV | Install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ clamav_packages }}"
  when: "{{ clamav_packages }}"

- name: Override ClamAV Apparmor
  copy:
    src: usr.sbin.clamd
    dest: /etc/apparmor.d/local/usr.sbin.clamd
    owner: root
    group: root
    mode: 0440
  notify:
   - apparmor enforce clamd
   - Restart ClamAV
