---

- name: Include variables suitable to our OS Family
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks suitable to our OS Family
  include: "{{ ansible_os_family }}.yml"

- name: Run Freshclam once
  command: /usr/bin/freshclam
  args:
    creates: /var/lib/clamav/daily.cld

- name: Start clamav daemon
  service:
    name: clamav-daemon
    state: started
    enabled: yes

- name: Start freshclam daemon
  service:
    name: clamav-freshclam
    state: started
    enabled: yes
