---

- name: Restart ClamAV
  service:
    name: clamav-daemon
    state: restarted

- name: Restart Freshclam
  service:
    name: clamav-freshclam
    state: restarted

- name: apparmor enforce clamd
  command: /usr/sbin/aa-enforce clamd
  notify: Restart ClamAV
